spring.application.name=matzip

spring.profiles.active=dev

spring.jwt.secret=${SPRING_JWT_SECRET}

server.port=8080

# DB 임시
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.database=mysql

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web.filter.CorsFilter=DEBUG
#logging.level.web.mvc.config.SecurityConfig=DEBUG # ??? SecurityConfig ??? ?? ???



# 환경설정 properties 임포트
spring.config.import=optional:application-secret.properties

iamport.rest-api-secret=9gmadZONetyUdRU8Bqd8u6uEb7iiUxjlM0fzUN2NLLI47qj6TM2azCHlx1Zujv2FkV6e5I7jsydQoUmc
iamport.rest-api-key=7155171530654661

# 카카오맵 API
kakao.map.base-url=https://dapi.kakao.com


# 단일 파일 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 요청 전체 크기 제한
spring.servlet.multipart.max-request-size=20MB
