spring.application.name=matzip

# DB ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/matzip?serverTimezone=Asia/Seoul
spring.datasource.username=kosta
spring.datasource.password=kosta295

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.database=mysql

# Naver OCR API ??
naver.ocr.secret-key=${NAVER_OCR_SECRET_KEY}
naver.ocr.invoke-url=${NAVER_OCR_INVOKE_URL}


#security key setting
spring.jwt.secret=SahL5G83mGzrulJzffw-eD7RqphsXluJPBwxu0ncBFo

# 환경설정 properties 임포트
spring.config.import=optional:application-secret.properties

iamport.rest-api-secret=9gmadZONetyUdRU8Bqd8u6uEb7iiUxjlM0fzUN2NLLI47qj6TM2azCHlx1Zujv2FkV6e5I7jsydQoUmc
iamport.rest-api-key=7155171530654661

# 국세청 사업자등록번호 검증 API 설정
nts.api.service-key=7CnAmYbndFbgS90ji/xwsSnIbJnUJvPGH/v6JdeAd27tnLWTd/3CDtxXZjGaUqFrtk8pvpMllqv9tvT57ddhwQ==

# 카카오맵 API
kakao.map.base-url=https://dapi.kakao.com
kakao.map.rest-api-key=8bcc2ef8d43dc528c96f2b9233e072a8