
# coolsms API
coolsms.api.key=${COOLSMS_API_KEY}
coolsms.api.secret=${COOLSMS_API_SECRET}
coolsms.api.from-number=${COOLSMS.API.FROM_NUMBER}

# 국세청 사업자등록번호 검증 API 설정
nts.api.service-key=${NTS_API_SERVICE_KEY}

# 카카오 맵 API
kakao.map.rest-api-key=${KAKAO_MAP_REST_API_KEY}

# AWS API
AWS_CREDENTIALS_ACCESSKEY=${AWS_CREDENTIALS_ACCESSKEY}
AWS_CREDENTIALS_SECRETKEY=${AWS_CREDENTIALS_SECRETKEY}
AWS_REGION_STATIC=${AWS_REGION_STATIC}
aws.s3.bucket=${AWS.S3.BUCKET}