spring.application.name=matzip

spring.profiles.active=dev

spring.jwt.secret=${SPRING_JWT_SECRET}

server.port=8080

# DB 임시
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.database=mysql

# 단일 파일 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 요청 전체 크기 제한
spring.servlet.multipart.max-request-size=20MB
